x-app: &app
  restart: unless-stopped

services:
  web:
    image: ghcr.io/dmitriykaftannikov/program-for-tutors:latest
    <<: *app
    labels:
      # Обязательно включить Traefik
      - "traefik.enable=true"

      # --- HTTPS ROUTER ---
      # Уникальный домен для приложения
      - "traefik.http.routers.tutor.rule=Host(`tutor.technocrew.ru`)"
      - "traefik.http.routers.tutor.entrypoints=websecure"
      - "traefik.http.routers.tutor.tls.certresolver=myresolver"

      # --- HTTP ROUTER (for redirect) ---
      - "traefik.http.routers.tutor-http.rule=Host(`tutor.technocrew.ru`)"
      - "traefik.http.routers.tutor-http.entrypoints=web"
      - "traefik.http.routers.tutor-http.middlewares=redirect-to-https"

      # --- Redirect middleware ---
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # --- INTERNAL PORT ---
      - "traefik.http.services.tutor.loadbalancer.server.port=80"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true